namespace API.classesEspelho;

public class Item
{
    public string? codigo { get; set; }
    public string? cod_pessoa { get; set; }
    public string? dt { get; set; }
    public string? data { get; set; }
    public string? data_mais_um { get; set; }
    public string? dtcadastro { get; set; }
    public string? cod_unidade { get; set; }
    public string? depto_cc { get; set; }
    public string? depto_conta { get; set; }
    public string? departamento { get; set; }
    public string? cod_centro_custo { get; set; }
    public string? centro_custo { get; set; }
    public string? nro_semana { get; set; }
    public string? nro_semana_ano { get; set; }
    public string? cod_empresa { get; set; }
    public string? empresa { get; set; }
    public string? descanso_minimo { get; set; }
    public string? cod_cargo { get; set; }
    public string? cargo { get; set; }
    public object? funcao { get; set; }
    public object? cod_pessoa_tipo_registro { get; set; }
    public string? obs { get; set; }
    public string? aceito { get; set; }
    public string? ndia_semana { get; set; }
    public string? dia_semana { get; set; }
    public string? situ_original { get; set; }
    public string? h_normais { get; set; }
    public string? desconto { get; set; }
    public string? h_noturna { get; set; }
    public string? h_extra { get; set; }
    public string? h_extra_feriado { get; set; }
    public object? foto { get; set; }
    public string? mc1 { get; set; }
    public string? mc2 { get; set; }
    public object? mc3 { get; set; }
    public object? mc4 { get; set; }
    public object? mc5 { get; set; }
    public object? mc6 { get; set; }
    public object? mc7 { get; set; }
    public object? mc8 { get; set; }
    public object? mc9 { get; set; }
    public object? mc10 { get; set; }
    public object? mc11 { get; set; }
    public object? mc12 { get; set; }
    public string? marcacao1 { get; set; }
    public string? marcacao2 { get; set; }
    public string? marcacao3 { get; set; }
    public string? marcacao4 { get; set; }
    public string? marcacao5 { get; set; }
    public string? marcacao6 { get; set; }
    public string? marcacao7 { get; set; }
    public string? marcacao8 { get; set; }
    public string? marcacao9 { get; set; }
    public string? marcacao10 { get; set; }
    public string? marcacao11 { get; set; }
    public string? marcacao12 { get; set; }
    public object? desconta_dsr { get; set; }
    public object? abona_dsr_descontar { get; set; }
    public object? justificativa { get; set; }
    public object? operacao_justificativa { get; set; }
    public object? gerar_extra { get; set; }
    public object? responder_indeferido { get; set; }
    public object? justificativa_qtd_aprovacao { get; set; }
    public object? gerar_noturna { get; set; }
    public object? justificativa_banco_horas { get; set; }
    public object? descricao_banco_horas { get; set; }
    public object? informar_hora_inicio_fim { get; set; }
    public string? banco_horas { get; set; }
    public string? cod_ponto_fechamento { get; set; }
    public object? cod_justificativa_ponto { get; set; }
    public string? extra_sab { get; set; }
    public string? h_noturno_menos_sumula60 { get; set; }
    public string? extra_dom { get; set; }
    public string? extra_semana { get; set; }
    public string? extra_folga { get; set; }
    public string? h_horas_sumula60 { get; set; }
    public object? extra_noturna_sab { get; set; }
    public object? extra_feriado { get; set; }
    public string? extra_facultativo { get; set; }
    public string? extra_noturna_feriado { get; set; }
    public object? extra_noturna_dom { get; set; }
    public string? extra_noturna_semana { get; set; }
    public object? extra_noturna_folga { get; set; }
    public string? pessoa { get; set; }
    public string? matricula { get; set; }
    public string? cpf { get; set; }
    public string? pis { get; set; }
    public string? compensado { get; set; }
    public string? falta_compensar { get; set; }
    public string? situacao { get; set; }
    public string? marcacao1_alterada { get; set; }
    public string? marcacao2_alterada { get; set; }
    public string? marcacao3_alterada { get; set; }
    public string? marcacao4_alterada { get; set; }
    public string? marcacao5_alterada { get; set; }
    public string? marcacao6_alterada { get; set; }
    public string? marcacao7_alterada { get; set; }
    public string? marcacao8_alterada { get; set; }
    public string? marcacao9_alterada { get; set; }
    public string? marcacao10_alterada { get; set; }
    public string? marcacao11_alterada { get; set; }
    public string? marcacao12_alterada { get; set; }
    public string? obs_marcacao_alterada { get; set; }
    public string? previsto { get; set; }
    public string? desconto_abonado { get; set; }
    public string? nao_faz_refeicao { get; set; }
    public string? dtdemissao { get; set; }
    public string? horas_abonada { get; set; }
    public string? tipo_pessoa { get; set; }
    public string? sem_extra_feriado { get; set; }
    public string? alterar_marcacao_ate { get; set; }
    public string? atraso { get; set; }
    public string? saida_antecipada { get; set; }
    public string? h_extra_noturna { get; set; }
    public object? cod_compensacao { get; set; }
    public string? he_noturno_final_ad_noturno { get; set; }
    public string? multiplicador_banco_horas { get; set; }
    public string? interjornada { get; set; }
    public string? bh_credito { get; set; }
    public string? bh_debito { get; set; }
    public string? cod_escala_padrao { get; set; }
    public object? dtjustificativa { get; set; }
    public object? login_justificativa { get; set; }
    public object? dtavaliador { get; set; }
    public object? dtalteracao { get; set; }
    public object? login_alteracao { get; set; }
    public object? login_avaliador { get; set; }
    public string? dia_dsr { get; set; }
    public string? tipo_salario { get; set; }
    public object? regime_juridico { get; set; }
    public string? horario { get; set; }
    public string? cod_horario { get; set; }
    public string? sexo { get; set; }
    public string? login_bloqueado { get; set; }
    public string? func_carga_horaria { get; set; }
    public string? sem_marcacao_refeicao { get; set; }
    public string? marcacao_fim_refeicao { get; set; }
    public string? adicional_noturno { get; set; }
    public string? tolerancia_hora_extra { get; set; }
    public string? tolerancia_atraso { get; set; }
    public string? tolerancia_saida { get; set; }
    public string? tolerancia_refeicao { get; set; }
    public string? inicio_adicional_noturno { get; set; }
    public string? fim_adicional_noturno { get; set; }
    public string? ad_noturno_reduzir_jornada { get; set; }
    public object? campo_livre { get; set; }
    public object? dtjustificativa_br { get; set; }
    public object? dtavaliador_br { get; set; }
    public string? nome_escala { get; set; }
    public object? descricao_escala { get; set; }
    public string? tipo { get; set; }
    public object? cod_sindicato_escala { get; set; }
    public string? codigo_legado_escala { get; set; }
    public object? cod_sindicato_empresa { get; set; }
    public object? cod_sindicato_pessoa { get; set; }
    public object? cod_sindicato_ponto { get; set; }
    public object? cod_sindicato_departamento { get; set; }
    public string? dtatual { get; set; }
    public object? sobreaviso_dobra { get; set; }
    public string? carga_horaria { get; set; }
    public string? sabado_folga_compensada { get; set; }
    public object? horas_descontar_intervalo { get; set; }
    public string? sobreaviso { get; set; }
    public string? sobreaviso_trabalhado { get; set; }
    public string? extensao_jornada { get; set; }
    public object? feriado { get; set; }
    public string? cargo_sem_adicional_noturno { get; set; }
    public string? intervalo_a_menor { get; set; }
    public string? extra_normal { get; set; }
    public string? extra_autorizada { get; set; }
    public string? extra_excessiva { get; set; }
    public object? soma_atrasos { get; set; }
    public string? comprovante_justificativa { get; set; }
    public object? htpc { get; set; }
    public object? cod_fechamento_automatico { get; set; }
    public object? j_aprovacao { get; set; }
    public object? cod_autorizacao_extra_pessoa { get; set; }
    public object? autorizacao_extra_n1 { get; set; }
    public object? autorizacao_extra_n2 { get; set; }
    public object? hora_extra_autorizada { get; set; }
    public object? login_aprovacao_n1 { get; set; }
    public object? dtaprovacao_n1 { get; set; }
    public object? dtcadastro_autorizacao { get; set; }
    public object? feriado_compensar { get; set; }
    public object? data_filho { get; set; }
    public object? data_pai { get; set; }
    public object? cid { get; set; }
    public object? crm { get; set; }
    public object? nome_medico { get; set; }
    public object? hrinicio { get; set; }
    public object? hrfim { get; set; }
    public object? j_avaliacao_nivel1 { get; set; }
    public object? j_avaliacao_nivel2 { get; set; }
    public object? j_avaliacao_alteracao_nivel1 { get; set; }
    public string? extrap50 { get; set; }
    public string? extrap55 { get; set; }
    public string? extrap60 { get; set; }
    public string? extrap65 { get; set; }
    public string? extrap70 { get; set; }
    public string? extrap75 { get; set; }
    public string? extrap80 { get; set; }
    public string? extrap85 { get; set; }
    public string? extrap90 { get; set; }
    public string? extrap95 { get; set; }
    public string? extrap100 { get; set; }
    public string? extrap110 { get; set; }
    public string? extrap120 { get; set; }
    public string? extrap130 { get; set; }
    public string? extrap150 { get; set; }
    public string? extrap200 { get; set; }
    public string? rg { get; set; }
    public object? msg_info_justificativa { get; set; }
    public object? comentario { get; set; }
    public string? carga_suplementar { get; set; }
    public object? hepi { get; set; }
    public object? carga_supl { get; set; }
    public object? junidade_horario { get; set; }
    public object? junidade_horario_htpc { get; set; }
    public string? extrap125 { get; set; }
    public string? t_h_he_menos_intervalo_a_menor { get; set; }
    //public int t_h_extra_dia_ponte { get; set; }
    public string? t_h_extra_dia_ponte { get; set; }
    //public int t_h_extra_facultativo { get; set; }
    public string? t_h_extra_facultativo { get; set; }
    public string? t_h_extra_extrafolga { get; set; }
    //public int t_h_sobreaviso_menos_trabalhado { get; set; }
    public string? t_h_sobreaviso_menos_trabalhado { get; set; }
    //public int maximo_marcacoes_dia { get; set; }
    public string? maximo_marcacoes_dia { get; set; }
    public string? t_h_extra_menos_intervalo_a_menor { get; set; }
    public string? jornadas { get; set; }
    public string? h_diver_abonada { get; set; }
    public bool? extra_intervalo { get; set; }
    public bool? ponto_facultativo { get; set; }
    public string? jornada { get; set; }
    //public int total_intervalos_ignorados { get; set; }
    public string? total_intervalos_ignorados { get; set; }
    //public int total_intervalo { get; set; }
    public string? total_intervalo { get; set; }
    //public int intervalo { get; set; }
    public string? intervalo { get; set; }
    public List<double?>? intervalos { get; set; }
    public List<string?>? hr_intervalos { get; set; }
    public string? jornada_cotia { get; set; }
    public string? hrentrada { get; set; }
    public string? hrini_intervalo { get; set; }
    public string? hrfim_intervalo { get; set; }
    public string? hrsaida { get; set; }
    public List<string?>? horarios { get; set; }
    public List<string?>? horarios_sem_dt { get; set; }
    public string? data_e_dsemana { get; set; }
    public string? alteracao { get; set; }
    public string? ultima_marcacao { get; set; }
    //public int pos_ultima_marcacao { get; set; }
    public string? pos_ultima_marcacao { get; set; }
    public string? atraso_nao_compensado { get; set; }
    public List<object?>? tp_intervalos { get; set; }
    public string? a_compensar { get; set; }
    public string? h_jornada { get; set; }
    //public int hrs_itinere { get; set; }
    public string? hrs_itinere { get; set; }
    public string? desconto_refeicao_auto { get; set; }
    public string? total_calculado { get; set; }
    public string? tempo_excedido_refeicao { get; set; }
    public string? entrada_antecipada { get; set; }
    public string? horas_apos_saida { get; set; }
    public string? desconto_tolerado { get; set; }
    //public int atraso_entrada { get; set; }
    public string? atraso_entrada { get; set; }
    public string? almoco_fora_janela { get; set; }
    public string? banco_horas_old { get; set; }
    public string? cod_banco_horas { get; set; }    
    //public int t_noturno_sumula { get; set; }
    //Newtonsoft.Json.JsonReaderException: Could not convert string? to integer: 2.283333. Path 'itens[0].t_noturno_sumula', line 1, position 6745.
    public string? t_noturno_sumula { get; set; }
    public string? h_extra_semana { get; set; }
    public string? h_extra_sab { get; set; }
    public string? h_extra_dom { get; set; }
    public string? h_extra_facultativo { get; set; }
    //public int h_extra_dia_ponte { get; set; }
    public string? h_extra_dia_ponte { get; set; }

    //public int h_extra_noturna_semana { get; set; }
    //Newtonsoft.Json.JsonReaderException: Could not convert string? to integer: 0.000000. Path 'itens[0].h_extra_noturna_semana'
    public string? h_extra_noturna_semana { get; set; }
    //public int h_extra_noturna_sab { get; set; }
    public string? h_extra_noturna_sab { get; set; }
    //public int h_extra_noturna_dom { get; set; }
    public string? h_extra_noturna_dom { get; set; }
    public string? h_extra_noturna_facultativo { get; set; }
    public string? h_extra_noturna_dia_ponte { get; set; }
    //public int h_extra_noturna_feriado { get; set; }
    public string? h_extra_noturna_feriado { get; set; }
    //public int h_extra_noturna_folga { get; set; }
    public string? h_extra_noturna_folga { get; set; }
    public string? carga { get; set; }
    public string? h_extra_noturna_sem_reducao { get; set; }

    //não vem em todos os casos:
    public string? sindicato_ponto { get; set; }
    public string? noturna_menos_he_noturna { get; set; }
    public string? extra_diurna { get; set; }
    public CpsDsr? cps_dsr { get; set; }
    public string? tipo_extra { get; set; }
    public string? extra_menos_intervalo_a_menor { get; set; }
    //public int multa_interjornada { get; set; }
    public string? multa_interjornada { get; set; }
    public string? extrapnoturna_100 { get; set; }
    public string? h_extra_folga { get; set; }
    
    //nao vem em todos os casos
    public string? adicional_noturno_real { get; set; }
    public string? t_h_extrap100 { get; set; }
    public string? t_h_extra_normal { get; set; }
    public string? t_h_extrapnoturna_100 { get; set; }
    public float? t_h_h_noturno_menos_sumula60 { get; set; }
    //public List<Extra> extra { get; set; }
    //public int dsr_qtd { get; set; }
    public string? dsr_qtd { get; set; }
    //public int dsr_desconto_feriado { get; set; }
    public string? dsr_desconto_feriado { get; set; }
    public bool? operou_banco_horas { get; set; }
    public string? tipo_calculo_escala { get; set; }
    public string? leitores { get; set; }
    public string? nro_leitores { get; set; }
    public List<object?>? mcs_descartadas { get; set; }
    public string? mc_direcao { get; set; }
    public string? mc_pausa { get; set; }
    public string? km { get; set; }
    public string? distancia { get; set; }
    public string? total_direcao { get; set; }
    public string? total_pausa { get; set; }

    //public List<Marcacao> json_marcacao1 { get; set; }
    //public List<Marcacao> json_marcacao2 { get; set; }
    public string? extra_ajustada { get; set; }
    public string? autorizada_pelo_sistema { get; set; }
    public string? autorizado_sistema_post { get; set; }
    public string? extra_nao_autorizada { get; set; }
    public string? extra_em_aprovacao { get; set; }
    public string? autorizada_posterior { get; set; }
    public string? extra_aut_automatico { get; set; }
    public string? extra_rejeitada { get; set; }
    public string? insalubridade { get; set; }
    public string? periculosidade { get; set; }
    public string? adicional_embarque { get; set; }
    public string? adicional_turno_trabalho { get; set; }
    public string? extra_mais_feriado { get; set; }
    public string? desconto_parcial { get; set; }
    public string? extra_contratual { get; set; }
    public string? falta { get; set; }
    public string? horas_pagas { get; set; }
    public string? h_extra_sem_folga { get; set; }
    public string? h_normais_mais_h_extra_menos_desconto { get; set; }
    public string? h_extrah_desconto_menos_banco_horas { get; set; }
    public string? bh_periodo { get; set; }
    public string? hr_normais { get; set; }
    public string? dsr_horista { get; set; }
    public string? soma_trab_extras_bh { get; set; }
    public string? saldo_acumulado { get; set; }
    public string? saldo_anterior { get; set; }

    public List<Html?>? html { get; set; }
    public string? cabecalho { get; set; }
    public List<object?>? meu_banco_horas { get; set; }
    //public int nivel_aprovador { get; set; }
    public string? nivel_aprovador { get; set; }
}